### ISSUE TITLE
PHP warning in RealTimeClient.php

### ISSUE THREAD

**Issue by stevenspasbo** [chrisgillis/slackwolf#49]
```PHP Warning:  Illegal string offset 'id' in vendor/coderstephen/slack-client/src/RealTimeClient.php on line 312```

**Comment by chrisgillis** [comment]
Looks like its an issue with the slack client package. Can look to see if a newer tagged release or master on that project has fixed the issue and if so update composer.json

**Comment by stevenspasbo** [comment]
I'm pretty sure it's coming from `SlackRTMClient.php`, but I haven't done much investigating.

**Comment by stevenspasbo** [comment]
Adding more details:

`PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Error creating resource: [message] fopen(): php_network_getaddresses: getaddrinfo failed: No address associated with hostname
[file] /home/slackwolf/slackwolf/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 282
[message] fopen(https://slack.com/api/im.open): failed to open stream: php_network_getaddresses: getaddrinfo failed: No address associated with hostname
[file] /home/slackwolf/slackwolf/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 282' in /home/slackwolf/slackwolf/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php:222
Stack trace:
#0 /home/slackwolf/slackwolf/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(286): GuzzleHttp\Handler\StreamHandler->createResource(Object(Closure))
#1 /home/slackwolf/slackwolf/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(52): GuzzleHttp\Handler\StreamHandler->createStream(Object(GuzzleHttp\Psr7\Request), Array)
#2 /home/slackwolf/slackwolf/vendor/guzzlehttp/guzzle/src/Pre in /home/slackwolf/slackwolf/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php on line 65`

I'll look into this more this weekend.
